name: promfun
services:
    prometheus:
        container_name: prometheus
        ports:
            - 9090
        image: prom/prometheus
        network_mode: "host"
        volumes:
            - ./prometheus/:/etc/prometheus/
            - prometheus_data:/prometheus
    alertmanager:
        container_name: alertmanager
        network_mode: "host"
        ports:
            - 9093
        image: quay.io/prometheus/alertmanager
    grafana:
        image: grafana/grafana:6.7.2
        container_name: grafana
        volumes:
          - grafana_data:/var/lib/grafana
          - ./grafana/provisioning:/etc/grafana/provisioning
        environment:
          - GF_SECURITY_ADMIN_USER=admin
          - GF_SECURITY_ADMIN_PASSWORD=admin
          - GF_USERS_ALLOW_SIGN_UP=false
        restart: unless-stopped
        expose:
          - 3000
        network_mode: "host"
        labels:
          org.label-schema.group: "monitoring"
volumes:
    prometheus_data: {}
    grafana_data: {}